name: package-mac
on:
  workflow_dispatch:
jobs:
  pkg:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.3
          cache: true
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Configure
        run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_ROOT_DIR" -DCPACK_PACKAGE_DIRECTORY="${{ github.workspace }}/artifact"
      - name: Build
        run: cmake --build build -j
      - name: Package DMG
        run: cd build && cpack
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: mmapper-dmg-${{ matrix.os }}
          path: artifact/**/*.dmg
